name: Purrsue
description: 'hai :3'
version: '${version}'

main: pro.fazeclan.river.purrsue.Purrsue
api-version: '26.2'
load: POSTWORLD

authors: [ riversflowing ]
website: https://github.com/flowingforever

dependencies:
  server:
    Jarona:
      load: BEFORE
      required: true